site:
  title: NeuVector documentation
  url: /
  start_page: 5.4@security:en:overview.adoc

content:
  sources:
    - url: https://github.com/rancher/neuvector-product-docs.git
      branches: [main, 5.3]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
